# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  DEPLOY_SERVER: "your_server_ip"
  DEPLOY_USER: "your_ssh_user"
  DEPLOY_PATH: "/var/www/html"

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - main

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - rsync -rav --delete build/ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "sudo systemctl restart nginx"
  only:
    - main
